# Robot Framework Mobile Tests for sauce_labs_demo
# Generated by MCP Appium Robot Mobile Generator

*** Settings ***
Documentation     Automated mobile tests for sauce_labs_demo
Library           AppiumLibrary
Suite Setup       Open Application
Suite Teardown    Close Application


*** Variables ***
$APP_PATH    app_tests/sauce_labs_demo/sauce_labs_demo.apk
${APPIUM_SERVER}    http://localhost:4723/wd/hub

# Appium Desired Capabilities
${PLATFORM_NAME}    Android
${AUTOMATION_NAME}    UiAutomator2
${DEVICE_NAME}    Android Emulator

# Login selectors
${'USERNAME_FIELD'}    test-Username
${'PASSWORD_FIELD'}    test-Password
${'LOGIN_BUTTON'}    test-LOGIN
$USERNAME    standard_user
$PASSWORD    secret_sauce

# Product page selectors
${'PRODUCTS_CONTAINER'}    //android.widget.ScrollView[@content-desc='test-PRODUCTS']
${'PRODUCT_ITEM'}    //android.view.ViewGroup[@content-desc='test-Item']
${'ADD_TO_CART_BUTTON'}    //android.view.ViewGroup[@content-desc='test-ADD TO CART']
${'PRODUCT_NAME'}    //android.widget.TextView[@content-desc='test-Item title']
${'CART_BUTTON'}    //android.view.ViewGroup[@content-desc='test-Cart']

# Checkout selectors
${'CHECKOUT_BUTTON'}    //android.view.ViewGroup[@content-desc='test-CHECKOUT']
${'FIRST_NAME_FIELD'}    //android.widget.EditText[@content-desc='test-First Name']
${'LAST_NAME_FIELD'}    //android.widget.EditText[@content-desc='test-Last Name']
${'POSTAL_CODE_FIELD'}    //android.widget.EditText[@content-desc='test-Zip/Postal Code']
${'CONTINUE_BUTTON'}    //android.view.ViewGroup[@content-desc='test-CONTINUE']
${'FINISH_BUTTON'}    //android.view.ViewGroup[@content-desc='test-FINISH']
${'SUCCESS_MESSAGE'}    //android.widget.TextView[@text='THANK YOU FOR YOU ORDER']


*** Keywords ***
Open Application
    AppiumLibrary.Open Application    ${APPIUM_SERVER}
    ...    platformName=${PLATFORM_NAME}
    ...    automationName=${AUTOMATION_NAME}
    ...    deviceName=${DEVICE_NAME}
    ...    app=${APP_PATH}
    ...    newCommandTimeout=60
    ...    appActivity=com.swaglabsmobileapp.MainActivity

Login
    [Arguments]    ${username}=${'USERNAME'}    ${password}=${'PASSWORD'}
    Wait Until Element Is Visible    ${'USERNAME_FIELD'}    timeout=30s
    Input Text    ${'USERNAME_FIELD'}    ${username}
    Input Text    ${'PASSWORD_FIELD'}    ${password}
    Click Element    ${'LOGIN_BUTTON'}
    Wait Until Element Is Visible    //android.view.ViewGroup[@content-desc='test-Inventory page']    timeout=10s

Add Product To Cart
    [Arguments]    ${index}=1
    Wait Until Element Is Visible    ${'PRODUCTS_CONTAINER'}    timeout=10s
    ${product_elements}=    Get WebElements    ${'PRODUCT_ITEM'}
    ${product}=    Get From List    ${product_elements}    ${index}
    ${product_name}=    Get Text    ${product}${'PRODUCT_NAME'}
    Click Element    ${product}${'ADD_TO_CART_BUTTON'}
    [Return]    ${product_name}

Go To Cart
    Click Element    ${'CART_BUTTON'}

Complete Checkout
    [Arguments]    ${first_name}=John    ${last_name}=Doe    ${postal_code}=12345
    Wait Until Element Is Visible    ${'CHECKOUT_BUTTON'}    timeout=10s
    Click Element    ${'CHECKOUT_BUTTON'}
    Wait Until Element Is Visible    ${'FIRST_NAME_FIELD'}    timeout=10s
    Input Text    ${'FIRST_NAME_FIELD'}    ${first_name}
    Input Text    ${'LAST_NAME_FIELD'}    ${last_name}
    Input Text    ${'POSTAL_CODE_FIELD'}    ${postal_code}
    Click Element    ${'CONTINUE_BUTTON'}
    Wait Until Element Is Visible    ${'FINISH_BUTTON'}    timeout=10s
    Click Element    ${'FINISH_BUTTON'}
    Wait Until Element Is Visible    ${'SUCCESS_MESSAGE'}    timeout=10s



*** Test Cases ***
Verify Login
    Login
    Element Should Be Visible    //android.view.ViewGroup[@content-desc='test-Inventory page']

Add Product To Cart
    Login
    ${product_name}=    Add Product To Cart
    Go To Cart
    Page Should Contain Text    ${product_name}

Complete Checkout Process
    Login
    Add Product To Cart
    Go To Cart
    Complete Checkout
    Element Should Be Visible    ${'SUCCESS_MESSAGE'}

Take Screenshot
    Capture Page Screenshot

Verify App Elements
    Page Should Contain Element    ${'USERNAME_FIELD'}
    Page Should Contain Element    ${'PASSWORD_FIELD'}
    Page Should Contain Element    ${'LOGIN_BUTTON'}
