# Robot Framework Web Tests for https://www.saucedemo.com/
# Generated by MCP Appium Robot Web Generator

*** Settings ***
Documentation     Automated web tests for https://www.saucedemo.com/
Library           Browser
Suite Setup       Setup Browser
Suite Teardown    Close Browser    ALL


*** Variables ***
$URL    https://www.saucedemo.com/
${'USERNAME_SELECTOR'}    input[data-test='username']
${'PASSWORD_SELECTOR'}    input[data-test='password']
${'LOGIN_BUTTON_SELECTOR'}    input[data-test='login-button']
${'USERNAME'}    standard_user
${'PASSWORD'}    secret_sauce

# Product page selectors
${'PRODUCT_ITEM_SELECTOR'}    .inventory_item
${'ADD_TO_CART_SELECTOR'}    button[data-test^='add-to-cart']
${'PRODUCT_NAME_SELECTOR'}    .inventory_item_name
${'CART_BUTTON'}    .shopping_cart_link

# Checkout selectors
${'CHECKOUT_BUTTON_SELECTOR'}    button[data-test='checkout']
${'FIRST_NAME_SELECTOR'}    input[data-test='firstName']
${'LAST_NAME_SELECTOR'}    input[data-test='lastName']
${'POSTAL_CODE_SELECTOR'}    input[data-test='postalCode']
${'CONTINUE_BUTTON_SELECTOR'}    input[data-test='continue']
${'FINISH_BUTTON_SELECTOR'}    button[data-test='finish']
${'SUCCESS_MESSAGE_SELECTOR'}    .complete-header


*** Keywords ***
Setup Browser
    New Browser    chromium    headless=False
    New Context    viewport={'width': 1280, 'height': 720}
    New Page    https://www.saucedemo.com/

Login
    [Arguments]    ${username}=${USERNAME}    ${password}=${PASSWORD}
    Fill Text    ${USERNAME_SELECTOR}    ${username}
    Fill Text    ${PASSWORD_SELECTOR}    ${password}
    Click    ${LOGIN_BUTTON_SELECTOR}
    Wait For Elements State    .inventory_container    visible    timeout=10s

Add Product To Cart
    [Arguments]    ${index}=0
    ${products}=    Get Elements    ${PRODUCT_ITEM_SELECTOR}
    ${product}=    Get From List    ${products}    ${index}
    ${product_name}=    Get Text    ${product} >> ${PRODUCT_NAME_SELECTOR}
    Click    ${product} >> ${ADD_TO_CART_SELECTOR}
    [Return]    ${product_name}

Go To Cart
    Click    ${CART_BUTTON}

Complete Checkout
    [Arguments]    ${first_name}=John    ${last_name}=Doe    ${postal_code}=12345
    Click    ${CHECKOUT_BUTTON_SELECTOR}
    Fill Text    ${FIRST_NAME_SELECTOR}    ${first_name}
    Fill Text    ${LAST_NAME_SELECTOR}    ${last_name}
    Fill Text    ${POSTAL_CODE_SELECTOR}    ${postal_code}
    Click    ${CONTINUE_BUTTON_SELECTOR}
    Click    ${FINISH_BUTTON_SELECTOR}
    Wait For Elements State    ${SUCCESS_MESSAGE_SELECTOR}    visible    timeout=10s



*** Test Cases ***
Verify Login
    Login
    Get Element    .inventory_container

Add Product To Cart
    Login
    ${product_name}=    Add Product To Cart
    Go To Cart
    Get Text    ${PRODUCT_NAME_SELECTOR}    ==    ${product_name}

Complete Checkout Process
    Login
    Add Product To Cart
    Go To Cart
    Complete Checkout
    Get Text    ${SUCCESS_MESSAGE_SELECTOR}

Verify Page Title
    ${title}=    Get Title
    Log    Page title: ${title}

Take Screenshot of Homepage
    Take Screenshot
